#pragma once
#include <GLFW\glfw3.h>

enum Keys
{
	KEY_SPACE = GLFW_KEY_SPACE,
	KEY_ESC = GLFW_KEY_ESCAPE,
	KEY_UP = GLFW_KEY_UP,
	KEY_DOWN = GLFW_KEY_DOWN,
	KEY_LEFT = GLFW_KEY_LEFT,
	KEY_RIGHT = GLFW_KEY_RIGHT,
	KEY_SHIFT = GLFW_KEY_LEFT_SHIFT,
	KEY_RSHIFT = GLFW_KEY_RIGHT_SHIFT,
	KEY_LCTRL = GLFW_KEY_LEFT_CONTROL,
	KEY_RCTRL = GLFW_KEY_RIGHT_CONTROL,
	KEY_LALT = GLFW_KEY_LEFT_ALT,
	KEY_RALT = GLFW_KEY_RIGHT_ALT,
	KEY_LSUPER = GLFW_KEY_LEFT_SUPER,
	KEY_RSUPER = GLFW_KEY_RIGHT_SUPER,
	KEY_TAB = GLFW_KEY_TAB,
	KEY_ENTER = GLFW_KEY_ENTER,
	KEY_BACKSPACE = GLFW_KEY_BACKSPACE,
	KEY_INSERT = GLFW_KEY_INSERT,
	KEY_DEL = GLFW_KEY_DELETE,
	KEY_PAGEUP = GLFW_KEY_PAGE_UP,
	KEY_PAGEDOWN = GLFW_KEY_PAGE_DOWN,
	KEY_HOME = GLFW_KEY_HOME,
	KEY_END = GLFW_KEY_END,
	//GLFW_KEY_KP_n Keypad numeric key n (n can be in the range 0..9),
	KEY_KP_DIVIDE = GLFW_KEY_KP_DIVIDE,
	KEY_KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY,
	KEY_KP_SUBTRACT = GLFW_KEY_KP_SUBTRACT,
	KEY_KP_ADD = GLFW_KEY_KP_ADD,
	KEY_KP_DECIMAL = GLFW_KEY_KP_DECIMAL,
	KEY_KP_EQUAL = GLFW_KEY_KP_EQUAL,
	KEY_KP_ENTER = GLFW_KEY_KP_ENTER,
	KEY_NUMLOCK = GLFW_KEY_NUM_LOCK,
	KEY_CAPSLOCK = GLFW_KEY_CAPS_LOCK,
	KEY_SCROLLLOCK = GLFW_KEY_SCROLL_LOCK,
	KEY_PAUSE = GLFW_KEY_PAUSE,
	KEY_MENU = GLFW_KEY_MENU
};

enum KeyState
{
	PRESS = GLFW_PRESS,
	RELEASE = GLFW_RELEASE
};

enum Buttons
{
	BUTTON_LEFT = GLFW_MOUSE_BUTTON_LEFT,
	BUTTON_RIGHT = GLFW_MOUSE_BUTTON_RIGHT,
	BUTTON_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE
};